// <auto-generated />
using System;
using BilgiYonetimSistemi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BilgiYonetimSistemi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BilgiYonetimSistemi.Models.Advisors", b =>
            {
                b.Property<int>("AdvisorID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvisorID"));

                b.Property<string>("Department")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("AdvisorID");

                b.ToTable("Advisors");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.Course", b =>
            {
                b.Property<int>("CourseID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseID"));

                b.Property<string>("CourseCode")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("CourseName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Credit")
                    .HasColumnType("int");

                b.Property<string>("Department")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<bool>("IsMandatory")
                    .HasColumnType("bit");

                b.HasKey("CourseID");

                b.ToTable("Courses");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.CourseQuotas", b =>
            {
                b.Property<int>("CourseId")
                    .HasColumnType("int");

                b.Property<int>("Quota")
                    .HasColumnType("int");

                b.Property<int>("RemainingQuota")
                    .HasColumnType("int");

                b.HasKey("CourseId");

                b.ToTable("CourseQuotas");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.CourseSelectionHistory", b =>
            {
                b.Property<int>("StudentID")
                    .HasColumnType("int");

                b.Property<DateTime>("SelectionDate")
                    .HasColumnType("datetime2");

                b.HasKey("StudentID");

                b.ToTable("CourseSelectionHistory");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.NonConfirmedSelections", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("CourseId")
                    .HasColumnType("int");

                b.Property<DateTime>("SelectedAt")
                    .HasColumnType("datetime2");

                b.Property<int>("StudentId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CourseId");

                b.HasIndex("StudentId");

                b.ToTable("NonConfirmedSelections");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.Student", b =>
            {
                b.Property<int>("StudentID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"));

                b.Property<int?>("AdvisorID")
                    .HasColumnType("int");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("EnrollmentDate")
                    .HasColumnType("datetime2");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.HasKey("StudentID");

                b.HasIndex("AdvisorID");

                b.ToTable("Students");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.StudentCourseSelections", b =>
            {
                b.Property<int>("CourseID")
                    .HasColumnType("int");

                b.Property<int>("StudentID")
                    .HasColumnType("int");

                b.Property<bool>("IsApproved")
                    .HasColumnType("bit");

                b.Property<DateTime>("SelectionDate")
                    .HasColumnType("date");

                b.Property<int>("SelectionID")
                    .HasColumnType("int");

                b.HasKey("CourseID", "StudentID");

                b.HasIndex("StudentID");

                b.ToTable("StudentCourseSelections");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.Transcripts", b =>
            {
                b.Property<int>("TranscriptID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TranscriptID"));

                b.Property<int>("CourseID")
                    .HasColumnType("int");

                b.Property<string>("Grade")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Semester")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("StudentID")
                    .HasColumnType("int");

                b.HasKey("TranscriptID");

                b.HasIndex("CourseID");

                b.HasIndex("StudentID");

                b.ToTable("Transcripts");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.Users", b =>
            {
                b.Property<int>("UserID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int?>("RelatedID")
                    .HasColumnType("int");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("nvarchar(450)");

                b.HasKey("UserID");

                b.HasIndex("Email")
                    .IsUnique();

                b.HasIndex("Username")
                    .IsUnique();

                b.ToTable("Users");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.CourseQuotas", b =>
            {
                b.HasOne("BilgiYonetimSistemi.Models.Course", "Course")
                    .WithMany()
                    .HasForeignKey("CourseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Course");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.CourseSelectionHistory", b =>
            {
                b.HasOne("BilgiYonetimSistemi.Models.Student", "Student")
                    .WithMany()
                    .HasForeignKey("StudentID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Student");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.NonConfirmedSelections", b =>
            {
                b.HasOne("BilgiYonetimSistemi.Models.Course", "Course")
                    .WithMany("NonConfirmedSelections")
                    .HasForeignKey("CourseId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("BilgiYonetimSistemi.Models.Student", "Student")
                    .WithMany("NonConfirmedSelections")
                    .HasForeignKey("StudentId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Course");

                b.Navigation("Student");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.Student", b =>
            {
                b.HasOne("BilgiYonetimSistemi.Models.Advisors", "Advisors")
                    .WithMany("Students")
                    .HasForeignKey("AdvisorID")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Advisors");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.StudentCourseSelections", b =>
            {
                b.HasOne("BilgiYonetimSistemi.Models.Course", "Course")
                    .WithMany("StudentCourseSelections")
                    .HasForeignKey("CourseID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("BilgiYonetimSistemi.Models.Student", "Student")
                    .WithMany("StudentCourseSelections")
                    .HasForeignKey("StudentID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Course");

                b.Navigation("Student");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.Transcripts", b =>
            {
                b.HasOne("BilgiYonetimSistemi.Models.Course", null)
                    .WithMany()
                    .HasForeignKey("CourseID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("BilgiYonetimSistemi.Models.Student", null)
                    .WithMany()
                    .HasForeignKey("StudentID")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.Advisors", b =>
            {
                b.Navigation("Students");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.Course", b =>
            {
                b.Navigation("NonConfirmedSelections");

                b.Navigation("StudentCourseSelections");
            });

            modelBuilder.Entity("BilgiYonetimSistemi.Models.Student", b =>
            {
                b.Navigation("NonConfirmedSelections");

                b.Navigation("StudentCourseSelections");
            });
#pragma warning restore 612, 618
        }
    }
}